[package]
name = "sui-gateway"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = { version = "1.0.57", features = ["backtrace"] }
async-trait = "0.1.53"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.80"
serde_with = { version = "1.14.0", features = ["hex"] }
schemars = "0.8.8"
jsonrpsee = { version = "0.13.1", features = ["full"] }
jsonrpsee-proc-macros = "0.13.1"
jsonrpsee-core = "0.13.1"
tracing = "0.1.34"
tokio = { version = "1.18.2", features = ["full"] }
futures = "0.3.21"
ed25519-dalek = { version = "1.0.1", features = ["batch", "serde"] }
prometheus_exporter = "0.8.4"
once_cell = "1.11.0"

sui-core = { path = "../sui-core" }
sui-config = { path = "../sui-config" }
sui-types = { path = "../sui-types" }
sui-json = { path = "../sui-json" }
sui-json-rpc-api = { path = "../sui-json-rpc-api" }
sui-open-rpc = { path = "../sui-open-rpc" }

move-core-types = { git = "https://github.com/move-language/move", rev = "4e15a34ecf155b7e2d9729d3b07f83c146149f02", features = ["address20"] }
mysten-network = { git = "https://github.com/MystenLabs/mysten-infra", rev = "ff5c1d69057fe93be658377462ca2875a57a0223" }
workspace-hack = { path = "../workspace-hack"}
