[package]
name = "sui-json-rpc-api"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
async-trait = "0.1.53"
anyhow = "1.0.57"
schemars = "0.8.8"
jsonrpsee = { version = "0.13.1", features = ["full"] }
jsonrpsee-proc-macros = "0.13.1"
jsonrpsee-core = "0.13.1"
once_cell = "1.12.0"
tracing = "0.1.34"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.80"
serde_with = { version = "1.14.0", features = ["hex"] }
colored = "2.0.0"
either = "1.6.1"
move-core-types = { git = "https://github.com/move-language/move", rev = "4e15a34ecf155b7e2d9729d3b07f83c146149f02", features = ["address20"] }
itertools = "0.10.3"

sui-types = { path = "../sui-types" }
sui-json = { path = "../sui-json" }
sui-open-rpc = { path = "../sui-open-rpc" }
sui-open-rpc-macros = { path = "../sui-open-rpc-macros" }

workspace-hack = { path = "../workspace-hack"}
